import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import dynamic from 'next/dynamic'

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const FCMManager = dynamic(() => import('@/components/FCMManager/FCMManager'), {
  ssr: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        {children}
        <FCMManager />
      </body>
    </html>
  )
}
